import os
import json
from typing import Optional
from groq import Groq
from pydantic import BaseModel, ValidationError
from dotenv import load_dotenv

load_dotenv()


class DigestOutput(BaseModel):
    title: str
    summary: str


PROMPT = """You are an expert AI news analyst specializing in summarizing technical articles, research papers, and video content about artificial intelligence.

Your role is to create concise, informative digests that help readers quickly understand the key points and significance of AI-related content.

Guidelines:
- Create a compelling title (5-10 words) that captures the essence of the content
- Write a 2-3 sentence summary that highlights the main points and why they matter
- Focus on actionable insights and implications
- Use clear, accessible language while maintaining technical accuracy
- Avoid marketing fluff - focus on substance

STRICT RULES:
- Output MUST be valid JSON only
- Do NOT include explanations, markdown, or extra text
- Do NOT wrap output in code blocks

JSON schema:
{
  "title": "string",
  "summary": "string"
}
"""


class DigestAgent:
    def __init__(self):
        self.client = Groq(api_key=os.getenv("GROQ_API_KEY"))
        self.model = "qwen/qwen3.6-27b"
        self.system_prompt = PROMPT

    def generate_digest(
        self,
        title: str,
        content: str,
        article_type: str
    ) -> Optional[DigestOutput]:
        try:
            user_prompt = (
                f"Create a digest for this {article_type}.\n\n"
                f"Title: {title}\n\n"
                f"Content:\n{content[:4000]}"
            )

            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": self.system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                temperature=0.7,
            )

            raw_text = response.choices[0].message.content

            # Parse JSON safely using regex to strip out conversational fluff/markdown
            import re
            
            # Strip <think>...</think> blocks generated by reasoning models
            cleaned_text = re.sub(r"<think>.*?</think>", "", raw_text, flags=re.DOTALL | re.IGNORECASE)
            
            match = re.search(r"\{.*\}", cleaned_text, re.DOTALL)
            if not match:
                raise ValueError("No JSON object found in model output")
            
            data = json.loads(match.group())
            return DigestOutput(**data)

        except (json.JSONDecodeError, ValidationError, ValueError) as e:
            print(f"Failed to parse model output. Error: {e}")
            print(f"RAW MODEL OUTPUT WAS:\n{raw_text}")
            return None
        except Exception as e:
            print(f"Error generating digest: {e}")
            return None
